Update complete_pipeline

diff --git a/complete_pipeline b/complete_pipeline
--- a/complete_pipeline
+++ b/complete_pipeline
@@ -280,7 +280,7 @@ HERE IS THE JENKINS PIPELINE FOR DEVELOPER BRANCH:
             }
         }
 
-        stage('Update Maven Version') {
+        stage('Update Maven Version') {        #before building the war file it will update the version of war file in pom.xml
             steps {
                 sh "mvn versions:set -DnewVersion=${APP_VERSION}"
             }
@@ -447,8 +447,16 @@ HERE IS THE JENKINS PIPELINE FOR RELEASE BRANCH IN APPLICATION REPO
 pipeline {
     agent any
 
+    tools {
+        maven 'maven'
+    }
+
+    parameters {
+        string(name: 'APP_VERSION', description: 'Version from dev (example: v1.0.1)')
+    }
+
     environment {
-        DOCKER_IMAGE = "sony9014/mydeploy"
+        DOCKER_IMAGE = "sony9014/mydeploy"         #image name  from docker registry 
     }
 
     stages {
@@ -459,7 +467,43 @@ pipeline {
             }
         }
 
-        stage('Get Latest Docker Version') {
+        stage('Use Version from Dev') {                      ####################################
+            steps {
+                script {
+                    if (!params.APP_VERSION) {
+                        error "APP_VERSION is required!"
+                    }
+                    env.APP_VERSION = params.APP_VERSION
+                    echo "Using Version: ${env.APP_VERSION}"
+                }
+            }
+        }
+
+        stage('Update Maven Version') {
+            steps {
+                sh "mvn versions:set -DnewVersion=${APP_VERSION}"
+            }
+        }
+
+        stage('Build WAR') {
+            steps {
+                sh "mvn clean package -DskipTests"
+            }
+        }
+
+        stage('Run Tests') {
+            steps {
+                sh "mvn test"
+            }
+        }
+
+        stage('Security Scan') {
+            steps {
+                sh "trivy fs --severity HIGH,CRITICAL --exit-code 1 ."
+            }
+        }
+
+        stage('Docker Build & Push') {
             steps {
                 script {
                     withCredentials([usernamePassword(
@@ -468,52 +512,68 @@ pipeline {
                         passwordVariable: 'DOCKER_PASS'
                     )]) {
 
-                        // Fetch ONLY version (no docker login noise)
-                        env.APP_VERSION = sh(
-                            script: """
-                                curl -s -u \$DOCKER_USER:\$DOCKER_PASS https://hub.docker.com/v2/repositories/${DOCKER_IMAGE}/tags?page_size=100 | \
-                                jq -r '.results[].name' | sort -V | tail -n1
-                            """,
-                            returnStdout: true
-                        ).trim()
-                    }
+                        sh """
+                            echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin
 
-                    echo "Promoting Docker Version: ${env.APP_VERSION}"
+                            docker build -t ${DOCKER_IMAGE}:${APP_VERSION} .
 
-                    if (!env.APP_VERSION) {
-                        error "No Docker version found!"
+                            docker push ${DOCKER_IMAGE}:${APP_VERSION}
+
+                            docker logout
+                        """
                     }
                 }
             }
         }
 
-        stage('Trigger QA Deployment') {
+        stage('Trigger Deployment Repo - QA') {
             steps {
                 script {
                     build job: 'deployment-repo/qa',
-                    propagate: true,   // change to false if you don’t want failure to affect this pipeline
                     parameters: [
-                        string(name: 'APP_VERSION', value: "${env.APP_VERSION}")
+                        string(name: 'APP_VERSION', value: "${APP_VERSION}")
                     ]
                 }
             }
         }
+        stage('Manual Approval for PreProd') {  #after deploying to QA we need to deploy in pre-prod through manual approval
+      steps {
+        timeout(time: 10, unit: 'MINUTES') {
+            input(
+                message: 'Approve deployment to PreProd?',
+                ok: 'Deploy',
+                submitter: 'sony'
+            )
+        }
+    }
+}        
+        stage('Trigger Deployment Repo - PreProd') {
+    steps {
+        script {
+            build job: 'deployment-repo/preprod',
+            parameters: [
+                string(name: 'APP_VERSION', value: "${APP_VERSION}")
+            ]
+        }
+    }
+}
     }
 
     post {
         success {
-            echo "✅ Release Pipeline Completed - QA Triggered"
+            echo "✅ Release Pipeline Completed → QA Deployment Triggered"
         }
         failure {
             echo "❌ Release Pipeline Failed"
         }
     }
 }
+
 *************************************************************************************************************************************
 when the image is pushed to docker registry from application repo (release branch) it will trigger QA branch in deployment repo and it 
 will deploy to QA server (QA-EC2)
-QA-SERVER/EC2(QUALITY-ANALYSIS) - It is the place where functional testing is done, where quality of the code is tested. If there are any bugs
-found then "FIX-BRANCH" is created from release, developers will work on the code and make the changes and merge the 
+QA-SERVER/EC2(QUALITY-ANALYSIS) - It is the place where functional testing is done, where quality of the code is tested. If there are 
+any bugs found then "FIX-BRANCH" is created from release, developers will work on the code and make the changes and merge the 
 "FIX-BRANCH" into "RELEASE-BRANCH"  and sync the changes in release branch with developer branch 
 
 HERE IS THE JENKINS PIPELINE FOR QA BRANCH IN DEPLOYMENT REPO:
